### ISSUE TITLE
Analyzing workspace on macOS

### ISSUE THREAD

**Issue by andreasproehl** [DSaladinCH/al-object-helper#51]
**Version: 2.2.10

**Describe the bug**
On macOS there is a problem with the appPath. The following changes in "AlApp.js" and "extension.js" will fix the problem:
```
if (!appPath.endsWith("\\")) {
  appPath += "\\";
}

change to 

if (!appPath.endsWith("/")) {
  appPath += "/";
}
```

**To Reproduce**
Open workspace with multiple projects on macOS.

**Expected behavior**
Objects in apps in folder .alpackages will be analyzed.

**Actual behavior**
Only local Objects from Apps in workspace are analyzed.

**Comment by DominicSaladin** [comment]
Hey @andreasproehl 

Thanks for reporting. I'm not currently developing the extension further, however I took a quick look at the problem and have included your fix. Could you install the prerelease of the extension manually and give me feedback?
[al-object-helper-2.2.11.zip](https://github.com/DSaladinCH/al-object-helper/files/9735846/al-object-helper-2.2.11.zip)

Thanks :)
Dominic

**Comment by andreasproehl** [comment]
Hi @DominicSaladin,

first of all, thank you for this great extension. The prerelease works well for me.

Thanks a lot
Andreas

**Comment by DominicSaladin** [comment]
Thank you for testing. I'm glade you like the extension :)
I've just updated the marketplace and the new version should be live in the next few hours.

Happy coding!
Dominic
