### ISSUE TITLE
Add support for app package cache

### ISSUE THREAD

**Issue by fvet** [DSaladinCH/al-object-helper#60]
**Version: v2.2.13**

**Describe the bug**
In one of the presentations at BC Techdays 2022 I saw someone using this VS Code extension to navigate to a base app object. I often find myself in searching for a base app object, without the need to declare a variable or to navigate to the object in the app.file via the AL Object Browser.

However, when trying to use this in one of my projects (using workspaces and a shared .alpackages packageCachePath), I'm not able to navigate to any of the base app objects (e.g. Customer). Is this supposed to be supported or is my setup invalid?

https://user-images.githubusercontent.com/25268332/205267204-8a93462f-cc71-4ceb-a843-957b8d996ea3.mp4

**Comment by DominicSaladin** [comment]
Hey @fvet 
I never saw a shared .alpackage folder in AL, so this is not implemented at the moment. Would you be so kind and show me where you configured this and how it works?
Then I would be able to implement this, so it also works with a shared .alpackage folder.

**Comment by fvet** [comment]
@DominicSaladin  My personal settings.json file contains following config:

`"al.packageCachePath": "C:\\Projects\\Dynavision\\.alpackages",`

Structure of my folders

![image](https://user-images.githubusercontent.com/25268332/205326837-8419ef14-7fed-4d33-8087-f584f6da8ffd.png)

![image](https://user-images.githubusercontent.com/25268332/205327140-40dbb0d7-ad4a-450c-ae5d-5199c5253293.png)

Having to maintain 25+ separate product apps, all with internal dependencies and all having the same System app, Base Application, ... led me towards sharing the packages and avoiding the need to keep duplicate package across projects.

**Comment by DominicSaladin** [comment]
@fvet I implemented the support for the custom app package cache. I will publish a new version this week and will close the issue then.

**Comment by fvet** [comment]
Great, I'll definitely give it a try soon!

**Comment by DominicSaladin** [comment]
Hey @fvet 
You are right, the first version of a package will be loaded. This is indeed not perfect, but I never saw someone using the alpackages folder like you.
But I will look into it, but can't guarantee a solution in next days, because of the christmas.

**Comment by DominicSaladin** [comment]
I implemented a new feature that will check your platform version and selects the latest package in your app cache. If a package with the same major version is available, this package will be used otherwise a higher version will be used :)
The extension will be published soon.
