### ISSUE TITLE
Activating extension 'DSaladin.al-object-helper' failed: The "path" argument must be of type string. Received an instance of Array.

### ISSUE THREAD

**Issue by Nuzuzar** [DSaladinCH/al-object-helper#85]
**Version: 2.3.4**

**Describe the bug**
Unable to use extension commands Ctrl+Alt+O - "command 'al-object-helper.openALObject' not found"

**To Reproduce**
1. Open VSCode 1.80.1
2. Attempt to use command Ctrl+Alt+O
3. See Warninig

**Expected behavior**
Open AL Object command should open

**Actual behavior**
Warning appears "command 'al-object-helper.openALObject' not found"

**Screenshots**
![image](https://github.com/DSaladinCH/al-object-helper/assets/49061330/5bb98204-68d8-4655-b4e9-e6267c91fbc8)

**Additional context**

Developer Tools console error shows
Activating extension 'DSaladin.al-object-helper' failed: The "path" argument must be of type string. Received an instance of Array. mainThreadExtensionService.ts:113 
$onExtensionActivationError @ mainThreadExtensionService.ts:113
N @ rpcProtocol.ts:455
M @ rpcProtocol.ts:440
H @ rpcProtocol.ts:370
G @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
w @ event.ts:1088
fire @ event.ts:1119
fire @ ipc.net.ts:650
Q.onmessage @ localProcessExtensionHost.ts:583

![image](https://github.com/DSaladinCH/al-object-helper/assets/49061330/c55df74c-5229-438a-ba8c-a9480ea69eab)

**Comment by DominicSaladin** [comment]
Thanks for reporting :)
I'm think I found the error and will provide you with a vsix package shortly

**Comment by Nuzuzar** [comment]
> Version 2.3.5 is now live

Installed and working - Thank you
